name: Cypress Tests

 

on:
  push:
    branches:
      - automatizacion-cypress
  pull_request:
    branches:
      - automatizacion-cypress

 

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: dime la fecha 
        run: date
      - run: ls -l
 

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: C:\pruebas_automatizadas_cypress\package.json
